# jdbc??mysql??
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?noAccessToProcedureBodies=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  type-aliases-package: com.test.login.entity
  mapper-locations: classpath:mapper/*.xml
